//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeCraft.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NodeCraft.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the CurrentUICulture property for all resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string FlowNodePalette_Add => ResourceManager.GetString("FlowNodePalette_Add", resourceCulture);

        internal static string FlowNodePalette_Description => ResourceManager.GetString("FlowNodePalette_Description", resourceCulture);

        internal static string FlowNodePalette_Title => ResourceManager.GetString("FlowNodePalette_Title", resourceCulture);

        internal static string FlowPort_condition => ResourceManager.GetString("FlowPort_condition", resourceCulture);

        internal static string FlowPort_false => ResourceManager.GetString("FlowPort_false", resourceCulture);

        internal static string FlowPort_flowIn => ResourceManager.GetString("FlowPort_flowIn", resourceCulture);

        internal static string FlowPort_input => ResourceManager.GetString("FlowPort_input", resourceCulture);

        internal static string FlowPort_inputA => ResourceManager.GetString("FlowPort_inputA", resourceCulture);

        internal static string FlowPort_inputB => ResourceManager.GetString("FlowPort_inputB", resourceCulture);

        internal static string FlowPort_output => ResourceManager.GetString("FlowPort_output", resourceCulture);

        internal static string FlowPort_suffix => ResourceManager.GetString("FlowPort_suffix", resourceCulture);

        internal static string FlowPort_true => ResourceManager.GetString("FlowPort_true", resourceCulture);

        internal static string FlowPort_value => ResourceManager.GetString("FlowPort_value", resourceCulture);

        internal static string NodeModel_DefaultName => ResourceManager.GetString("NodeModel_DefaultName", resourceCulture);
    }
}
