<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NodeCraft\NodeCraft.csproj" />
    <ProjectReference Include="..\NodeCraft.Flow\NodeCraft.Flow.csproj" />
    <ProjectReference Include="..\NodeCraft.Vision.StereoCamera\NodeCraft.Vision.StereoCamera.csproj" />
    <ProjectReference Include="..\NodeCraft.PluginSample\NodeCraft.PluginSample.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\NodeCraft.PluginSample\PrivateDependency\PluginPrivateDependency.csproj" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyMetadata Include="BuildConfiguration" Value="$(Configuration)" />
    <AssemblyMetadata Include="BuildTargetFramework" Value="$(TargetFramework)" />
  </ItemGroup>
</Project>
